In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
data = pd.read_csv('Sample.csv')

In [33]:
#data.to_string()

In [5]:
data.head()

samples  Glucose  Fructose  Isomaltose  Saccharose Raffinose  Turanose  \
0    Go07     32.7      32.1         0.8         2.1         -       1.1   
1    Bo07     20.7      28.4         1.0         1.0         -       1.2   
2    Mo07     32.8      44.1         0.6         0.7         -       0.6   
3    Pa07     27.1      37.0         1.2         1.8       0.2       1.3   
4    Ca07     19.5      26.3         1.4         1.5       0.2       1.0   

   Maltose  G/W   F/G   F+G  Total sugars Adulteration  
0      2.4  2.0  2.00  64.8          71.2        Ideal  
1      1.0  1.2  1.71  49.1          53.3         Less  
2      1.9  2.2  2.98  76.9          80.7         More  
3      0.9  1.5  2.09  64.1          69.5        Ideal  
4      0.6  1.0  1.38  45.8          50.5         Less

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   samples       15 non-null     object 
 1   Glucose       15 non-null     float64
 2   Fructose      15 non-null     float64
 3   Isomaltose    15 non-null     float64
 4   Saccharose    15 non-null     float64
 5   Raffinose     15 non-null     object 
 6   Turanose      15 non-null     float64
 7   Maltose       15 non-null     float64
 8   G/W           15 non-null     float64
 9   F/G           15 non-null     float64
 10  F+G           15 non-null     float64
 11  Total sugars  15 non-null     float64
 12  Adulteration  15 non-null     object 
dtypes: float64(10), object(3)
memory usage: 1.6+ KB


In [7]:
data.isnull().sum()

samples         0
Glucose         0
Fructose        0
Isomaltose      0
Saccharose      0
Raffinose       0
Turanose        0
Maltose         0
G/W             0
F/G             0
F+G             0
Total sugars    0
Adulteration    0
dtype: int64

In [8]:
df = data.drop(['samples', 'Raffinose', 'Turanose','G/W', 'F/G', 'F+G', 'Total sugars'], axis=1)

In [9]:
df.head()

Glucose  Fructose  Isomaltose  Saccharose  Maltose Adulteration
0     32.7      32.1         0.8         2.1      2.4        Ideal
1     20.7      28.4         1.0         1.0      1.0         Less
2     32.8      44.1         0.6         0.7      1.9         More
3     27.1      37.0         1.2         1.8      0.9        Ideal
4     19.5      26.3         1.4         1.5      0.6         Less

In [10]:
parameters = ['Glucose', 'Fructose', 'Isomaltose', 'Saccharose', 'Maltose']
y_features = df['Adulteration']
X=df[parameters].values

In [11]:
X

array([[32.7, 32.1,  0.8,  2.1,  2.4],
       [20.7, 28.4,  1. ,  1. ,  1. ],
       [32.8, 44.1,  0.6,  0.7,  1.9],
       [27.1, 37. ,  1.2,  1.8,  0.9],
       [19.5, 26.3,  1.4,  1.5,  0.6],
       [27.9, 38.4,  1.2,  1.1,  0.9],
       [29.7, 40.1,  1.7,  1.8,  2.4],
       [27.9, 40.4,  1.7,  2. ,  1.7],
       [26.4, 38.6,  1.6,  2.2,  2.9],
       [27.5, 37. ,  1.2,  1.1,  1.6],
       [26.2, 36. ,  1.7,  1.8,  1.4],
       [19.8, 34.4,  2.1,  2. ,  0.7],
       [26.2, 37.9,  1. ,  1.8,  1.1],
       [26.5, 38.7,  1.9,  3.8,  1.2],
       [26.2, 37.7,  3.3,  3.7,  1.4]])

In [12]:
y_features

0     Ideal
1      Less
2      More
3     Ideal
4      Less
5     Ideal
6      More
7      more
8     Ideal
9     Ideal
10    Ideal
11     Less
12    IDeal
13    Ideal
14     More
Name: Adulteration, dtype: object

In [13]:
X.shape

(15, 5)

In [14]:
Y = df['Adulteration'].values

In [15]:
Y

array(['Ideal', 'Less', 'More', 'Ideal', 'Less', 'Ideal', 'More', 'more',
       'Ideal', 'Ideal', 'Ideal', 'Less', 'IDeal', 'Ideal', 'More'],
      dtype=object)

In [16]:
train_x, test_x, train_y, test_y=train_test_split(X, Y, test_size=0.25, random_state=0)

In [17]:
train_x

array([[26.2, 37.7,  3.3,  3.7,  1.4],
       [19.5, 26.3,  1.4,  1.5,  0.6],
       [32.8, 44.1,  0.6,  0.7,  1.9],
       [26.5, 38.7,  1.9,  3.8,  1.2],
       [26.2, 36. ,  1.7,  1.8,  1.4],
       [27.9, 40.4,  1.7,  2. ,  1.7],
       [19.8, 34.4,  2.1,  2. ,  0.7],
       [27.1, 37. ,  1.2,  1.8,  0.9],
       [32.7, 32.1,  0.8,  2.1,  2.4],
       [27.9, 38.4,  1.2,  1.1,  0.9],
       [26.2, 37.9,  1. ,  1.8,  1.1]])

In [18]:
train_x.shape

(11, 5)

In [19]:
test_x

array([[20.7, 28.4,  1. ,  1. ,  1. ],
       [29.7, 40.1,  1.7,  1.8,  2.4],
       [26.4, 38.6,  1.6,  2.2,  2.9],
       [27.5, 37. ,  1.2,  1.1,  1.6]])

In [20]:
test_x.shape

(4, 5)

In [21]:
from sklearn.naive_bayes import GaussianNB

In [22]:
model = GaussianNB()

In [23]:
model.fit(train_x, train_y)

GaussianNB()

In [24]:
model.predict(test_x)

array(['Ideal', 'Ideal', 'Ideal', 'Ideal'], dtype='<U5')

In [25]:
model.predict([[20.0, 1.5, 1.6, 2.6, 70]])

array(['Ideal'], dtype='<U5')

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [27]:
prediction = model.predict(test_x)

confusion_matrix = confusion_matrix(test_y, prediction)
confusion_matrix

array([[2, 0, 0],
       [1, 0, 0],
       [1, 0, 0]], dtype=int64)

In [28]:
accuracy_score = accuracy_score(test_y, prediction)
print(accuracy_score)

0.5


In [29]:
print('misclassified values : ', (test_y != prediction).sum())

misclassified values :  2


In [32]:
#import seaborn as sns
#import matplotlib.pyplot as plt
#plt.figure(figsize = (10,7))
#sns.heatmap(confusion_matrix, annot=True, fmt='d')
#plt.xlabel('Predicted')
#plt.ylabel('Truth')